### ISSUE TITLE
Probleme bei wkhtmltopdf Installation

### ISSUE THREAD

**Issue by mangp** [windele/alarmdisplay-ffw#14]
Hallo.
Ich wende mich nun mit einem erneuten Problem an euch.

Ich habe das Tool wkhtmltopdf per Befehl sudo apt-get install wkhtmltopdf auf meinem System installiert.
Jedoch finde ich die Datei .xsessionrc nicht, welche ich laut Doku in mein Homeverzeichnis kopieren sollte damit das Tool funktioniert.
Kann mir da bitte jemand helfen?
Danke im Voraus

**Comment by TobsA13** [comment]
Mal 'ls -la' gemacht um auch versteckte Dateien anzuzeigen?
