### ISSUE TITLE
Keine Anzeige bei Aufruf der Seite / Kein Zugriff auf Admin-Seite

### ISSUE THREAD

**Issue by mangp** [windele/alarmdisplay-ffw#15]
Hallo, ich bin leider immer noch nicht so weit, dass ich das System testweise in Betrieb nehmen kann.

Ich habe nun eine Neuinstallation ausgeführt. Jetzt habe ich das Problem dass ich die Seite zwar aufrufen kann, mir aber nichts angezeigt wird.
Wenn ich die Administrator-Seite aufrufen möchte, wird mir angezeigt, dass ich keine Rechte habe diese Seite aufzurufen.

Danke für eure erneute Hilfe

**Comment by windele** [comment]
Hallo,

ich glaube, das Dein Problem mit den Dateiberechtigungen zu tun hat. Das Webserver-Programm kann nicht auf den Ordner zugreifen.

Versuche, die Dateiberechtigungen für das Verzeichnis entsprechend zu setzen.

z.B. `sudo chmod -R 755 /var/www/alarmdisplay`

Viele Grüße,
Stefan

**Comment by mangp** [comment]
Hallo
DANKE! Hat funktioniert

Aber leider wird mir auf der "Startseite" des Alarmdisplays nichts angezeigt

**Comment by windele** [comment]
Hallo,
was heißt "nichts"? Wird eine weiße Seite angezeigt? Ist im Quelltext etwas sichtbar?

**Comment by mangp** [comment]
Genau, es wird nur eine weiße Seite angezeigt.
Der Quelltext sieht so aus:

<!DOCTYPE html>
<html>
<head>
<title>Alarmdisplay - Freiwillige Feuerwehr Leoben-Göss</title>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<script type="text/javascript" src="js/alarmdisplay.js"></script>
<link rel='stylesheet' href='css/screen.css' type='text/css' media='screen, projection'>
</head>

**Comment by mangp** [comment]
<!DOCTYPE html>
<html>
<head>
<title>Alarmdisplay - Freiwillige Feuerwehr Leoben-Göss</title>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<script type="text/javascript" src="js/alarmdisplay.js"></script>
<link rel='stylesheet' href='css/screen.css' type='text/css' media='screen, projection'>
</head>

**Comment by mangp** [comment]
#<!DOCTYPE html>
#<html>
#<head>
#<title>Alarmdisplay - Freiwillige Feuerwehr Leoben-Göss</title>
#<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
#<script type="text/javascript" src="js/alarmdisplay.js"></script>
#<link rel='stylesheet' href='css/screen.css' type='text/css' media='screen, projection'>
#</head>

**Comment by windele** [comment]
Dann bitte prüfen, ob die index.php verändert wurde - normalerweise sollte es laufen und mehr ausgeben, als von Dir im editierten Posting gezeigt.

**Comment by mangp** [comment]
index.php wurde nicht verändert. Habe gerade nochmal die Originaldatei nachkopiert, funktioniert trotzdem nicht

**Comment by windele** [comment]
Dann wäre es hilfreich, den ausgegebenen Quelltext hier zu posten, um eine Fehleranalyse durchführen zu können.

Ist der Webserver korrekt installiert und wird PHP ausgeführt?

**Comment by mangp** [comment]
[source.txt](https://github.com/windele/alarmdisplay-ffw/files/205802/source.txt)

**Comment by webtp** [comment]
gibt es hier eine Lösung? Ich habe auch eine weiße Seite beim aufruf des Monitors und im Adminimenü sehe ich nur den Logout, das Logo und einen Strich =(

**Comment by HyP3r-** [comment]
@webtp am besten ein neues Issue erstellen in dem du genau beschreibst was wo nicht geht, mit Logs und Screenshots.
