### ISSUE TITLE
Adminibereich funktioniert nur teilweise

### ISSUE THREAD

**Issue by webtp** [windele/alarmdisplay-ffw#16]
Ich habe ein Problem beim öffnen des admin-Bereich.
Bild:
![fehler_darstellung_adminbereich](https://cloud.githubusercontent.com/assets/22799976/19325413/508e2350-90c6-11e6-91bd-73aab4958776.png)

Dort werden nur der Logout, Roterbalken das Musterlogo sowie der Name der FW angezeigt. Mein OS ist Ubuntu LTS Client x86 16.04
Apache 2.4.18
php 7.0

Darstellung geht weder unter Linux Firefox noch unter Windows 7. Was genau fehlt kann ich euch leider nicht sagen da ich es noch nie gesehen habe.

Vielleicht könnt ihr mir kurz sagen wie ich die Logs bekomme dann reiche ich diese nach, danke.

**Comment by HyP3r-** [comment]
Bei mir sieht das so aus:

![2016-10-12_215930](https://cloud.githubusercontent.com/assets/8094242/19325712/a8dca328-90c7-11e6-88ae-ac3ca51c8e89.png)

Unter `/var/log/apache2` findest du von `apache2` den `error.log`, poste das mal. Poste hier bitte außerdem den Quelltext den du vom Webserver bei der Anfrage erhälst. Des Weiteren würde ich mal php5 versuchen, vielleicht ist der ganze Code einfach zu php7 nicht mehr kompatibel.

Dieses Verhalten wundert mich allgemein schon sehr da weiterer Code z.B. das darunter kommende Formular usw. direkt im PHP Skript ein paar Zeilen darunter ausgeführt wird aber du auch keine Fehler angezeigt bekommst.

**Comment by webtp** [comment]
Errorlog:

[error.txt](https://github.com/windele/alarmdisplay-ffw/files/525567/error.txt)


Quelltext:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="de" lang="de">
 <head>
  <title>Administration Alarmdisplay</title>
 <link type="text/css" href="../css/screen.css" rel="stylesheet" />
 <link type="text/css" href="../css/blitzer/jquery-ui-1.8.21.custom.css" rel="stylesheet" />
<script type="text/javascript" src="../js/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="../js/jquery-ui-1.8.21.custom.min.js"></script>
<script type="text/javascript">
			$(function(){

				// Accordion
				$("#accordion").accordion({ header: "h3" });

				// Tabs
				$('#tabs').tabs();

				// Dialog
				$('#dialog').dialog({
					autoOpen: false,
					width: 600,
					buttons: {
						"Ok": function() {
							$(this).dialog("close");
						},
						"Cancel": function() {
							$(this).dialog("close");
						}
					}
				});

				// Dialog Link
				$('#dialog_link').click(function(){
					$('#dialog').dialog('open');
					return false;
				});

				// Datepicker
				$('#datepicker').datepicker({
					inline: true
				});

				// Slider
				$('#slider').slider({
					range: true,
					values: [17, 67]
				});

				// Progressbar
				$("#progressbar").progressbar({
					value: 20
				});

				//hover states on the static widgets
				$('#dialog_link, ul#icons li').hover(
					function() { $(this).addClass('ui-state-hover'); },
					function() { $(this).removeClass('ui-state-hover'); }
				);



			});

jQuery(function(jQuery)  
    {  
     jQuery.datepicker.regional['de'] = {clearText: 'löschen', clearStatus: 'aktuelles Datum löschen',  
                closeText: 'schließen', closeStatus: 'ohne änderungen schließen',  
                prevText: '<zurück', prevStatus: 'letzten Monat zeigen',  
                nextText: 'Vor>', nextStatus: 'nächsten Monat zeigen',  
                currentText: 'heute', currentStatus: '',  
                monthNames: ['Januar','Februar','März','April','Mai','Juni',  
                'Juli','August','September','Oktober','November','Dezember'],  
                monthNamesShort: ['Jan','Feb','Mär','Apr','Mai','Jun',  
                'Jul','Aug','Sep','Okt','Nov','Dez'],  
                monthStatus: 'anderen Monat anzeigen', yearStatus: 'anderes Jahr anzeigen',  
                weekHeader: 'Wo', weekStatus: 'Woche des Monats',  
                dayNames: ['Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag'],  
                dayNamesShort: ['So','Mo','Di','Mi','Do','Fr','Sa'],  
                dayNamesMin: ['So','Mo','Di','Mi','Do','Fr','Sa'],  
                dayStatus: 'Setze DD als ersten Wochentag', dateStatus: 'Wähle D, M d',  
                dateFormat: 'dd.mm.yy', firstDay: 1,   
                initStatus: 'Wähle ein Datum', isRTL: false};  
     jQuery.datepicker.setDefaults(jQuery.datepicker.regional['de']);  
    });  


		</script>

</head>



<body><div><img src='../images/logo.png' align='right'><br /><a href='logout.php'>Logout</a><br><h2>Administration Alarmdisplay FFW-LK Abt. Lauda</h2></div><form action='http://IP/alarmdisplay/administrator/index.php' method='POST'><div id='tabs'>

<ul>



```

**Comment by HyP3r-** [comment]
Bei genauerem hinsehen ist mir folgendes aufgefallen:

`[Wed Oct 12 21:43:10.168792 2016] [:error] [pid 4946] [client 10.130.128.98:55798] PHP Fatal error:  Uncaught Error: Call to a member function fetch_row() on boolean in /var/www/html/alarmdisplay/administrator/index.php:186\nStack trace:\n#0 {main}\n  thrown in /var/www/html/alarmdisplay/administrator/index.php on line 186, referer: http://10.130.128.239/alarmdisplay/administrator/login.php`

Das passiert an dieser Stelle im Code: https://github.com/windele/alarmdisplay-ffw/blob/master/administrator/index.php#L195

Die Funktion `fetch_row` kann nicht ausgeführt werden wenn `$tabs` [null](http://php.net/manual/en/mysqli-result.fetch-row.php#refsect1-mysqli-result.fetch-row-returnvalues) durch einen Fehlerhaften SQL Query ist.

**Das bedeutet also die Tabelle `tbl_adm_params` bei dir kaputt ist.**

**Comment by webtp** [comment]
Mein Import ist aber problemlos gelaufen :(
Ich versuchte es nochmal und as Ergebnis war: Der Import wurde erfolgreich abgeschlossen, 28 Abfragen wurden ausgeführt. (alarmdisplay_database.sql)

Könntest du vielleicht die IP-Addressen raus nehmen? Ich hab die txt nicht durchgeschaut =(

**Comment by HyP3r-** [comment]
In dem SQL Skript war noch ein Fehler drin: https://gist.github.com/HyP3r-/21ac98bc962a645e48c0fc04b7e57551

Versuchs doch bitte nochmal.

**Comment by webtp** [comment]
Leider keine Änderung.

**Comment by HyP3r-** [comment]
Hast auch mal php5 versucht zu verwenden?

**Comment by webtp** [comment]
Hab gerade folgendes Probiert:

```
sudo apt-get install php7.0 php5.6 php5.6-mysql php-gettext php5.6-mbstring php-xdebug libapache2-mod-php5.6 libapache2-mod-php7.0

sudo a2dismod php7.0 ; sudo a2enmod php5.6 ; sudo service apache2 restart
sudo ln -sfn /usr/bin/php5.6 /etc/alternatives/php
```
Leider ohne Erfolg. Hab ich vielleicht etwas falsch gemacht?

**Comment by HyP3r-** [comment]
Scheint schon zu stimmen, poste doch bitte nochmal die aktuelle `error.log`.

**Comment by webtp** [comment]
Anbei die neue Error.log:
[error.txt](https://github.com/windele/alarmdisplay-ffw/files/527521/error.txt)

**Comment by HyP3r-** [comment]
Scheint einfach immer noch der gleiche Fehler zu sein. Was kommt raus wenn du mit z.B. phpMyAdmin oder in der Konsole folgende Abfrage machst: `SELECT tab, title FROM tbl_adm_params WHERE (acc=0 AND line=0) GROUP BY tab`

**Comment by webtp** [comment]
![phpmyadmin](https://cloud.githubusercontent.com/assets/22799976/19356240/6d393a9c-916d-11e6-866e-0543531818e7.png)

Mal eine blöde Frage, aktualisiert sich das hier von alleine:
https://gist.github.com/HyP3r-/21ac98bc962a645e48c0fc04b7e57551

**Comment by HyP3r-** [comment]
Durch die sehr aktuelle Version von MySQL bei dir funktionieren einige SQL Statements mit GROUP BY bei dir nicht mehr.  [Das liegt daran, dass das Default Behaviour von MySQL geändert wurde](http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by). Schalte bitte die Option `ONLY_FULL_GROUP_BY` bei deiner MySQL Engine ab. Ich werde für die nächste Version die SQL Statements verbessern.

**Comment by webtp** [comment]
Falls noch jemand Probleme hat anbei der Lösungsweg:
`Nano /etc/mysql/conf.d/disable_strict_mode.cnf`
Insert:
```
[mysqld]
sql_mode=IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```
Restart MYSQL-service:
`sudo service mysql restart`
Bestätigen von “strict SQL mode:
`sudo mysql -i -BN -e 'SELECT @@sql_mode' | grep -E 'ONLY_FULL_GROUP_BY|STRICT_TRANS_TABLES'`
