### ISSUE TITLE
Anzeige Test fehlgeschlagen

### ISSUE THREAD

**Issue by webtp** [windele/alarmdisplay-ffw#17]
Hallo,

ich wollte den Anzeige Test durchführen:
`/var/spool/hylafax/bin/faxrcvd \
  "configuration/testfax.tif" \
  "ttyACM0" \
  "000000001"
`
Leider funktioniert das ganze bei mir nicht:

```
/var/spool/hylafax/bin/faxrcvd: Zeile 30: bin/common-functions: Datei oder Verzeichnis nicht gefunden
Usage: /var/spool/hylafax/bin/faxrcvd file devID commID error-msg [ callID-1 [ callID-2 [ ... [ callID-n ] ] ] ]
/var/spool/hylafax/bin/faxrcvd: Zeile 37: hfExit: Befehl nicht gefunden

FATAL ERROR: /var/www/html/alarmdisplay/configuration/etc/setup.cache is missing!

The file /var/www/html/alarmdisplay/configuration/etc/setup.cache is not present.  This
probably means the machine has not been setup using the faxsetup(8)
command.  Read the documentation on setting up HylaFAX before you
startup a server system.

/var/spool/hylafax/bin/faxrcvd: Zeile 52: hfExit: Befehl nicht gefunden
/var/spool/hylafax/bin/faxrcvd: Zeile 62: etc/setup.cache: Datei oder Verzeichnis nicht gefunden
/var/spool/hylafax/bin/faxrcvd: Zeile 121: -e: Befehl nicht gefunden
/var/spool/hylafax/bin/faxrcvd: Zeile 123: SetupPrivateTmp: Befehl nicht gefunden
/var/spool/hylafax/bin/faxrcvd: Zeile 125: parseFaxInfo: Befehl nicht gefunden
/var/spool/hylafax/bin/faxrcvd: Zeile 225: -fFaxMaster: Befehl nicht gefunden
/var/spool/hylafax/bin/faxrcvd: Zeile 224: CreateMailMessage: Befehl nicht gefunden
Cuneiform for Linux 1.1.0
Magick: Unable to open file (/var/spool/hylafax/configuration/testfax.tif) reported by magick/blob.c:2828 (OpenBlob)
PHP Warning:  file_get_contents(/tmp/alarm/latest-fax.txt): failed to open stream: No such file or directory in /var/www/html/alarmdisplay/ocr/readfile.php on line 56
PHP Stack trace:
PHP   1. {main}() /var/www/html/alarmdisplay/ocr/readfile.php:0
PHP   2. file_get_contents() /var/www/html/alarmdisplay/ocr/readfile.php:56
/var/spool/hylafax/bin/faxrcvd: Zeile 245: CleanupPrivateTmp: Befehl nicht gefunden
```

Faxsetup und faxmodem hab ich eigentlich beide durchgeführt -.-*

**Comment by TobsA13** [comment]
Hi,

versuch mal den Befehl aus dem `/var/spool/hylafax` Verzeichniss auszuführen. Also 
`cd /var/spool/hylafax
bin/faxrcvd /var/www/alarmdisplay/configuration/testfax.tif` "ttyACM0" "000000001"`

**Comment by webtp** [comment]
Jetzt kam folgendes: 

```
administrator@srvmo01:/var/spool/hylafax$ /var/spool/hylafax/bin/faxrcvd \ "configuration/testfax.tif" \ "ttyACM0" \ "000000001"
Usage: /var/spool/hylafax/bin/faxrcvd file devID commID error-msg [ callID-1 [ callID-2 [ ... [ callID-n ] ] ] ]
```
Aber am Display erscheint nichts. Sofern es funktioniert müsste doch dort eine Änderung zu sehen sein?

**Comment by TobsA13** [comment]
Bleib mal in dem Verzeichnis und kopiere den Befehl genau so rein: 

`bin/faxrcvd "/var/www/alarmdisplay/configuration/testfax.tif" "ttyACM0" "000000001" ""`

**Comment by webtp** [comment]
Jetzt kommt folgendes:
`administrator@srvmo01:/var/spool/hylafax$ bin/faxrcvd "/var/www/alarmdisplay/configuration/testfax.tif" "ttyACM0" "000000001" ""
bin/common-functions: Zeile 158: COULD: Befehl nicht gefunden
bin/common-functions: Zeile 158: EITHER: Befehl nicht gefunden
bin/common-functions: Zeile 159: export: `/VAR/WWW/ALARMDISPLAY/CONFIGURATION/TESTFAX.TIF': Ist kein gültiger Bezeichner.
bin/common-functions: Zeile 159: EITHER: Befehl nicht gefunden
Cuneiform for Linux 1.1.0
Magick: Unable to open file (/var/spool/hylafax//var/www/alarmdisplay/configuration/testfax.tif) reported by magick/blob.c:2828 (OpenBlob)
PHP Warning:  file_get_contents(/tmp/alarm/latest-fax.txt): failed to open stream: No such file or directory in /var/www/html/alarmdisplay/ocr/readfile.php on line 56
PHP Stack trace:
PHP   1. {main}() /var/www/html/alarmdisplay/ocr/readfile.php:0
PHP   2. file_get_contents() /var/www/html/alarmdisplay/ocr/readfile.php:56
`

**Comment by HyP3r-** [comment]
Wenn du eine Meldung bekommst mit einem `Unable to open file` was machst du dann? Du schaust ob die Datei vorhanden ist, **und** ob die Datei auch lesbar ist mit dem Dienst die später die Datei lesen können muss. Kannst du das überprüfen? Einfache Linux _fertigkeiten_ sollen bei solch einem _komplexen System_ schon vorhanden sein. Des Weiteren solltest du auch in der Lage sein ein `man faxrcvd` einzugeben um dir ein Bild zu machen welche Argumente **deine** faxrcvd benötigt.

**Comment by webtp** [comment]
@HyP3r- : Heute mit dem falschen Fuß aufegstanden ;-D

Datei ist vorhanden chmod 755 wurde gesetzt:
```
administrator@srvmo01:/var/spool/hylafax$ ls -la /var/www/html/alarmdisplay/configuration/
insgesamt 596
drwxr-xr-x  2 administrator administrator   4096 Okt 14 12:15 .
drwxr-xr-x 10 administrator administrator   4096 Okt 12 20:15 ..
-rw-rw-r--  1 administrator administrator  19110 Okt 12 21:33 alarmdisplay_database.sql
-rwxr-xr-x  1 administrator administrator   3568 Okt 27  2015 config.ttyACM0_USR_USB_MODEM
-rwxr-xr-x  1 administrator administrator   6631 Okt 27  2015 faxrcvd
-rwxr-xr-x  1 administrator administrator 543069 Okt 27  2015 ils.traineddata
-rwxr-xr-x  1 administrator administrator  15076 Okt 27  2015 testfax.tif
-rwxr-xr-x  1 administrator administrator     81 Okt 27  2015 .xsessionrc
-rwxr-xr-x  1 administrator administrator    798 Okt 27  2015 zusatzsoftware.txt
```
Wenn ich nicht mal wusste wie ich an das Log komme, was meinst du wie die Antwort auf deine retorische Frage lautet? Nein ich habe keine Ahnung von Linux und meine Fertigkeiten sind gleich NULL.

Aus `man faxrcvd` wurde ich nicht schlauer. Wie das öffnen des Testfax funktionieren soll sagt mir nicht mal google.

**Comment by HyP3r-** [comment]
Poste doch bitte über GitHub Gists den Inhalt deiner faxrcvd Datei, das Skript ist etwas groß.

**Comment by TobsA13** [comment]
Dein erstes Problem ist das `faxrcvd` einen relativen Pfad erwartet ich dir aber einen Absoluten hingeschrieben habe. Ich würde jetzt zuerst mal das Testfax in das `recvq` Verzeichnis kopieren, dort hin kommen später auch die Faxe von HylaFax. Und dann mit `bin/faxrcvd "recvq/testfax.tif" "ttyACM0" "000000001" ""` nochmal testen.

Das zweite Problem sind wie Hyp3r- schon gesagt hat fehlende Linux Kenntnisse und das kann sehr blöd ausgehen. Auch denke ich, dass du das System mal Produktiv in der Feuerwehr benutzen willst und dafür sollte man schon einiges wissen. Angefangen bei Absicherung bis zu Updates...

**Comment by webtp** [comment]
Link zum Git: https://gist.github.com/webtp/6b4c989a368069cf3b8200454f0df10d

@TobsA13 
Nach dem ich die Datei wie beschrieben kopiert habe und wieder im verzeichnis `/var/spool/hylafax` den von dir geschriebenen Befehl `bin/faxrcvd "recvq/testfax.tif" "ttyACM0" "000000001" ""` ausgeführt habe, hat alles funktioniert:

```
administrator@srvmo01:/var/spool/hylafax$ bin/faxrcvd "recvq/testfax.tif" "ttyACM0" "000000001" ""
Cuneiform for Linux 1.1.0
Mitteiler: Faith
Strasse: An der Kreppe
Haus-Nr: 25
Ort: 86473 Ziemetshausen
Einsatzgrund: 7.3 Anfrage Feuerwehr
Prio: 0
Bemerkung: TEST
Dispo 0: Ziemetshausen
Dispo 1: Ziemetshausen 11/1
Dispo 2: Ziemetshausen 40/1
Dispo 3: Ziemetshausen 41/1
Dispo 4: Ziemetshausen 48/1
Dispo 5: Memmenhausen 44/1
PHP Fatal error:  Call to undefined function utf8_decode() in /var/www/html/alarmdisplay/ocr/readfile.php on line 176
PHP Stack trace:
PHP   1. {main}() /var/www/html/alarmdisplay/ocr/readfile.php:0
```
![alarmdisplay_anzeigetest](https://cloud.githubusercontent.com/assets/22799976/19478814/47920c6c-9544-11e6-8bd5-6114095a7b11.png)

Jetzt sollte man das Testfax mal per USB-Modem an den hylafax Server senden?

**Comment by TobsA13** [comment]
Genau würde ich so machen. Du kannst mit `faxstat -r` den aktuellen Status von HylaFax anschauen.

**Comment by HyP3r-** [comment]
Wie schon in der **README.md** beschrieben kannst du ein einmal empfangenes Fax nicht nochmal an dich selber senden, die Auflösung veringert sich durch das erneute senden so stark das HylaFax bei mir nichts mehr lesen konnte. Aber versuchen kannst du das gerne.

**Comment by webtp** [comment]
@HyP3r- Muss ich nur php5 oder auch apache2 und mysql utf8_decode beibringen?
Faxen teste ich morgen und melde mich wieder :)

**Comment by HyP3r-** [comment]
Ich weiß nicht welche Version von PHP du verwendest. Du musst aber `php-xml` oder `php7.0-xml` als Paket installieren damit du diese Funktion bekommst.

**Comment by webtp** [comment]
```
 php -v
PHP 5.6.26-2+deb.sury.org~xenial+1 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```
Ändern muss man dann noch die php.ini Datei unter /etc/php.ini, /etc/php5/php.ini, oder /etc/php5/apache2/php.ini, liegen kann. Dort fügt man folgendes ein:

`default_charset = "UTF-8"`
Ist das richtig?

**Comment by HyP3r-** [comment]
Ich glaube an den Konfigurationsdateien musst du nichts abändern.

Alles weitere findest du hier:

http://stackoverflow.com/a/20707899/5232865
https://www.google.de/search?q=Call+to+undefined+function+utf8_decode

**Comment by webtp** [comment]
@HyP3r- : Jetzt hab ich nochmal Fragen zu uft8-decode. Wo hast du gesehen das mir das Fehlt?
Wenn ich wie beim ersten Link die Funktion testen möchte `var_dump(function_exists('utf8_decode'));` kommt folgende Meldung: ```
var_dump(function_exists('utf8_decode'));
-bash: Syntaxfehler beim unerwarteten Wort »function_exists«
```
Das Paket php-xml habe ich installiert ich weis nicht wie ich die Funktion testen soll.

**Comment by HyP3r-** [comment]
In deinem Post von gestern kommt folgende Zeile vor:

`PHP Fatal error:  Call to undefined function utf8_decode() in /var/www/html/alarmdisplay/ocr/readfile.php on line 176`

Deswegen habe ich damit angefangen.

Offensichtlich hast du einen PHP Schnipsel `var_dump(function_exists('utf8_decode'));` in die Kommandozeile eingegeben, das Funktioniert so leider nicht. Diesen Schnipsel musst du mit dem PHP Interpreter ausführen. Das kannst du damit erreichen, dass du diesen Schnipsel in eine PHP Datei speicherst und diese dann ausführst.

**Comment by webtp** [comment]
Ok. Der Fehler kam also beim Test-Fax. Dies habe ich gerade nochmal eingespielt:

```
administrator@srvmo01:/var/spool/hylafax$ bin/faxrcvd "recvq/testfax.tif" "ttyACM0" "000000001" ""
Cuneiform for Linux 1.1.0
Mitteiler: Faith
Strasse: An der Kreppe
Haus-Nr: 25
Ort: 86473 Ziemetshausen
Einsatzgrund: 7.3 Anfrage Feuerwehr
Prio: 0
Bemerkung: TEST
Dispo 0: Ziemetshausen
Dispo 1: Ziemetshausen 11/1
Dispo 2: Ziemetshausen 40/1
Dispo 3: Ziemetshausen 41/1
Dispo 4: Ziemetshausen 48/1
Dispo 5: Memmenhausen 44/1
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/alarmdisplay/ocr/readfile.php:179
Stack trace:
#0 {main}
  thrown in /var/www/html/alarmdisplay/ocr/readfile.php on line 179
```
Zeile 179 in readfile.php:
  ` $ch = curl_init();`

**Comment by TobsA13** [comment]
http://lmgtfy.com/?q=curl+php+installieren

**Comment by HyP3r-** [comment]
@TobsA13 YMMD :smile: 

@webtp http://stackoverflow.com/a/8199206/5232865

**Comment by webtp** [comment]
Jetzt mal schluss mit lustig und das anprangern ein Ende. 
PHP-Version ist php7.0
Der Faxserver nimmt das Fax an kommt auch ein OK an den Absender. Jedoch landet das Fax nicht in der DB. Wie findet man hier die Ursache am besten?

**Comment by TobsA13** [comment]
Einfach die Kette nach und nach durchgehen

- Kommt das Fax richtig an
- Liegt das Fax dort wo es soll
- Funktioniert das Auslesen des Faxes (Mal Manuell starten)
- Funktioniert das Verarbeiten der Daten
- Funktioniert das DB Schreiben

**Comment by webtp** [comment]
Das Fax wird laut Absender empfangen und mit OK bestätigt.
Die Daten liegen im Format .tif unter /var/spool/hylafax/recvq/ 
Namen sind aktuell fax000000002.tif und fax000000003.tif
Wenn ich das Fax manuell starte funktioniert dieses nicht Befehl und Shellrückgabe:
```
administrator@srvmo01:/var/spool/hylafax$ bin/faxrcvd "recvq/fax000000003.tif" "ttyACM0" "000000001" ""
Cuneiform for Linux 1.1.0
Mitteiler:
Strasse: An der Kreppe
Haus-Nr: ' 25
Ort: 86473 Ziemetshausen
Einsatzgrund:
Prio: 0
Bemerkung: TEST
Dispo 0: GZ FF Ziemetshausen
Dispo 1: Ziemetshausen 11/1
Dispo 2: GZ FL Ziemetshausen 40/1
Dispo 3: Ziemetshausen 41/1
Dispo 4: FL Ziemetshausen 48/1
Dispo 5: GZ FL Nemmenhausen 44/1
```
Danach ist leider kein Eintrag in der DB.

Wie kann ich die letzten zwei Punkte testen?

**Comment by TobsA13** [comment]
Dafür gehst du jetzt in die `ocr/readfile.php` rein und gehst nach und nach den Ablauf durch.

Du kannst dir mit `var_dump($VARIABLE)` noch eigene Debug Ausgaben im Quellcode hinzufügen.

Ist in deinem Fall ganz einfach, aber versuch es mal selbst herauszufinden.

**Comment by webtp** [comment]
Ich vermute das es an der Qualität des Fax liegt. Die Texterkennung findet keinen Einsatzgrund und auf Zeile 140 steht das bei keinem Einsatzgrund die Übertragung in die Datenbank nicht vorgenommen wird.
Hab ich hier recht? Sollte dies der Fall sein wäre es jetzt meines erachtens sinnvoll die orc an das Fax unserer Leitstelle anzupassen.

**Comment by HyP3r-** [comment]
Die [Regulären Ausdrücke](https://github.com/windele/alarmdisplay-ffw/blob/master/ocr/readfile.php#L69) müssen an das Alarmfax deiner Rettungsleiststelle angepasst werden. 

Da du ja aber im Moment das Fax von unserer Leistelle dir reinschickst könnte es daran liegen das die OCR Probleme hat, poste doch mal das was die OCR so erkennt.

**Comment by webtp** [comment]
OCR als TXT:[latest-fax.txt](https://github.com/windele/alarmdisplay-ffw/files/542035/latest-fax.txt)
Also hab ich recht und ich pass das ganze jetzt an die Leitstelle hier an?

**Comment by HyP3r-** [comment]
Ja das Schlagwort kann nicht mehr erkennt werden, da statt **Schlagw**, **Schlagv** erkannt wird.

**Comment by webtp** [comment]
Bei der Erkennung ist es da so dass man von oben nach unten geht?

**Comment by HyP3r-** [comment]
Ich habe das System aus Reguläre Ausdrücke umgestellt die das komplette Dokument am Stück durchforsten. Mit etwas Ignore Case, Character Wildcards, usw. sind eigentlich ganz robust gegen OCR Störungen.

**Comment by webtp** [comment]
@HyP3r- 

> Außerdem kann ich dir anbieten das wir Gemeinsam das ganze System einrichten, dann ist es für uns (mich) einfacher und für dich schneller (direktere Kommunikation).
Steht dein Angebot noch?

**Comment by HyP3r-** [comment]
@webtp 
Grundsätzlich mal ja, poste hier doch bitte deine E-Mail Adresse oder andere Kontaktmöglichkeit, ich werde auf dich zukommen.

**Comment by webtp** [comment]
web.tp(at]web.de
