### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by BorderCounter** [windele/alarmdisplay-ffw#20]
Ich verzweifle gerade an den Anpassungen der readfile.php...

Der "Kopf" der LS Nord sieht genau so aus wie in der testfax.tif, jedoch haben wir bei Einsatzgrund, Einsatzmittel und Bemerkung etwas anderes.

---------- Einsatzgrund -----------
Brand Nebengebäude, Personen im Gebäude
---------- Einsatzmittel -----------
Name : Alarmiert : Ausgerückt
FF Musterstadt 41/1
FL Kreisbrandrat 1
PP Polizei 18/22
----------- Bemerkung ------------
Anfahrt über Michaelsweg.
Bereitstellungsraum am Platz

Ich muss also irgendwie alle Zeilen die nach Einsatzmittel kommen in ein Array schreiben bis Bemerkung kommt und dann alle Zeilen bis zum Faxende in das nächste Array.

Hat jemand einen Tip für mich, wie ich die Datei anpassen muss?

**Comment by webtp** [comment]
Hallo BorderCounter,
du musst den Code der Readfile.php von Zeile 68 bis 100 auf dein Alarmfax anpassen.
Warum willst du alles nach Bemerkung in ein Array packen?
Was für ein OS und welche PHP version setzt du ein?

Gruß

**Comment by BorderCounter** [comment]
Hey,
das Problem ist vielmehr, dass bei deinem Fax vor jedem Einsatzmittel ein Name steht, bei mir jedoch alle einsatzmittel mit ohne ein prefix wie z.B. "Name =" in der Liste stehen. Somit kann ich nicht nach diesem Zeichen suchen. 
Ich nutze Ubuntu 16.04 und PHP 7.1

**Comment by TobsA13** [comment]
Nutz doch den Regex von webtp und trenn dann nach Zeilen auf. Dann hast du im Array
`["Name : Alarmiert : Ausgerückt", "FF Musterstadt 41/1", "FL Kreisbrandrat 1", "PP Polizei 18/22"]`
stehen.

**Comment by BorderCounter** [comment]
Dämlicher Denkfehler meinerseits - funktioniert jetzt :)
Danke euch allen!!
