### ISSUE TITLE
not Found

### ISSUE THREAD

**Issue by TheSpion** [windele/alarmdisplay-ffw#21]
Hallo zusammen,

habe das Alarmdisplay wie in der Anleitung beschrieben auf einem Raspberry 3 installiert.

Beim starten der Webseite erhalte ich die Fehlermeldung Not Found.

Hatte jemand das Problem schon mal?

Vielen Dank

**Comment by windele** [comment]
Sorry, den Fehler hatte ich noch nicht.

 

Stimmen die Berechtigungen unter /var/www/alarmdisplay, so dass der Http-Server darauf zugreifen kann?

 

Was ergibt das Logfile des Webservers: access.log?

 

viele Grüße

Stefan
