### ISSUE TITLE
neue ABek - Tesseract-Problem 

### ISSUE THREAD

**Issue by maxend** [windele/alarmdisplay-ffw#23]
Hallo,

seit der Einführung der neuen ABek stehen wir vo dem Problem, dass die Raute (#) nicht als solche, sondern als 8 erkannt wird.
Funktioniert zwar trotzdem, ist aber unschön und verwirrend.

Hat jemand die tesseract ils-Sprachdatei schon darauf angepasst?
Verwendet man stattdessen die deutsche Sprachdatei, werden bei uns alle : als = behandelt.

Gruß
Max

**Comment by nordi81** [comment]
Falls es noch aktuell sein sollte, du kannst mit einem php-script nach "= " suchen und durch ": " jeweils mit Leerzeichen ersetzen lassen.
