### ISSUE TITLE
Route und Einsatzort funktionieren mit Google Maps nur noch mit Bezahlung

### ISSUE THREAD

**Issue by webtp** [windele/alarmdisplay-ffw#25]
Hallo zusammen,

Google hat seinen Dienst Maps am 11.06.2018 geändert und die Nutzung der Karten für den Einsatzort und die Route sind nicht mehr kostenfrei (Siehe Zitat). Gibt es von Seiten der Entwickler einen Plan wie damit umgegangen wird? Ändert man die Karte auf Openstreetmap oder ähnliches?

Hier mal ein Beispiel wie das ganze aktuell aussieht:
![d84eedf6-7d97-4d7a-8db3-c52bc5d87229](https://user-images.githubusercontent.com/22799976/42185647-f28060b6-7e49-11e8-8f37-6719aa7df681.jpg)

Auf dem Ausdruck wird es dann sehr dunkel abgedruckt was auch nicht gerade  hilfreich ist ;-)

> Allgemeine Fragen zu den Preisen
>
> Was wurde an der Preisgestaltung geändert?
>
>  Ab dem 11. Juni 2018 gilt für Maps, Routes und Places ein neues nutzungsbasiertes Preismodell, das 
> Ihnen mehr Flexibilität und eine bessere Kontrolle über die Nutzung unserer APIs bietet: Sie können sie  in beliebigem Umfang verwenden und bezahlen nur für die tatsächliche Nutzung im jeweiligen Monat. 
 Wir möchten außerdem darauf hinweisen, dass sich am 11. Juni die Preise für Maps, Routes und Places  ändern. Weitere Informationen finden Sie in der Preisübersicht und auf der Seite mit den  
> API->spezifischen Änderungen bei der Abrechnung. Für Kunden mit der Premiumoption erfolgt die 
> Umstellung auf das neue Preismodell, wenn ihr aktueller Vertrag ausläuft.

Gruß

webtp

**Comment by windele** [comment]
Hallo,

leider habe ich die Änderung bei Google auch erst durch die Auswirkungen am Alarmdisplay mitbekommen :-(

Ich habe mich damals für Google entschieden, da bei der initialen Entwicklung der Software die Hausnummern-Abdeckung von Open-Streetmap einfach zu gering war, um verlässliche Ergebnisse in unserem Gebiet zu liefern. Dies hat sich aber deutlich verbessert, so dass ich mir einen Schwenk auf OpenStreetmap sehr gut vorstellen könnte.

Leider habe ich aktuell nicht viel Zeit, um in die Programmierung einzusteigen. Eventuell gibt es Entwickler, die sich hier einbringen können?

Eine Alternative wäre die Auswertung der Koordinaten, die die Leitstelle seit kurzem mitschickt. Diese sind im Gauß-Krüger-Format angegeben, die versteht z.B. der BayernAtlas der Vermessungsverwaltung. Ein Routing/Navigation für die Anfahrt ist hier aber leider nicht möglich.

Viele Grüße
Stefan

**Comment by Hubschra01** [comment]
Hallo,
Zur Zeit versuche ich ob sich die Anzeige bei uns in der FFw etablieren kann.
dafür habe ich nur ein schnelles System aufgesetzt. Da ich das gleiche Problem hatte mit GMaps versuche ich die OSM Karte zuverwenden. Muss noch ein paar Sachen testen. Zur Zeit gibt es noch ein paar Haker is halt quick-and-dirty.  
Routenberechnung gibt es in der Version nicht. 
Dafür wird der Openfiremap Layer verwendet d.h eingetragene Hydranten werden angezeigt. 
Einstellungen per Admin Oberfläche fehlen auch....
Gruß André

**Comment by HyP3r-** [comment]
Die Einbindung der Karte werde ich in der nächsten Version neu implementieren.

**Comment by windele** [comment]
Super, vielen herzlichen Dank! Bis wann wird die Version ca. fertig sein?

**Comment by webtp** [comment]
>  windele commented 5 hours ago
Super, vielen herzlichen Dank! Bis wann wird die Version ca. fertig sein?

Das ist eine sehr gute Frage. Wie bekommt man hier News und Updates?

**Comment by Hubschra01** [comment]
Möchte sich jemand das OSM Modul anschauen? Weiß nur nicht wie man das hier machen kann.

**Comment by windele** [comment]
Das wäre super - leider weiß ich das auch nicht. Vielleicht kann jemand helfen?Andere Idee für Hyp3r für die nächste Version: kann man die von der Leitstelle übermittelten ‎Koordinaten auswerten und abspeichern?Die Koordinaten könnte man für ein genaues Geoding verwenden, wenn OpenStreetmap kein genaues Erge‎bnis für die Hausnummer liefert. Umrechnung von Gauss-Krüger auf Lat/Lon kann ich liefern wenn Bedarf wäre.

**Comment by HyP3r-** [comment]
Ich werde auf jeden Fall auch in der neuen Version die Koordinaten bevorzugt auswerten und mit diesen die Route berechnet, das wird auch in meiner Wehr gefordert. Auch unsere Leitstelle liefert die Koordinaten im Gauss-Krüger System, die Umrechnung ist aber kein Problem. Grundsätzlich habe ich vor die neue Version (2) mit Python Django im Backend und die Oberfläche (Frontend) mit modernen JavaScript (ECMAscript 7) webpack und babel zu entwickeln.

News zu dem Projekt bekommt ihr durch das Beobachten dieses Repositories. Ich hoffe das ich diesen Sommer Urlaub dazu komme, zumindest die meisten Features umzusetzen. Versprechen kann ich aber dazu leider nichts.

**Comment by Hubschra01** [comment]
@HyP3r- Sammelst du schon Ideen für die neue Version? Ich hätte da noch so ein oder zwei...

**Comment by HyP3r-** [comment]
Einfach als Issue hier veröffentlichen, ich werde das dann als Enhancement markieren und weiter bearbeiten.

**Comment by Hubschra01** [comment]
@HyP3r- Kannst Du dir mal das Kartenmodul von mir anschauen ob das bei dir funktioniert.

**Comment by webtp** [comment]
Gibt es schon was neues von eurer Alternative? Ich möchte gerne den Kameraden wieder eine sauber dargestellte Karte anbieten :(

**Comment by windele** [comment]
Von mir leider noch nicht - hast Du schon das Modul von @Hubschra01 probiert?

**Comment by webtp** [comment]
Wo finde ich das Modul von @Hubschra01 ?

**Comment by Hubschra01** [comment]
Sollte eigentlich in meinem Fork sein. Als patch-1. Das Modul hat den gleichen Namen wie das für Goggle maps. Deine alte logischerweise sichern falls es doch nicht geht...

**Comment by Hubschra01** [comment]
Zur Zeit ehr nicht, da ich noch ein paar andere Probleme mit der Anzeige lösen muss, damit sie bei uns die Faxe bzw. die Emails zuverlässiger Auswerten kann. Irgendwie hat unsere Leitstelle ein ganz tollen Faxaufbau sich ausgesucht... ;-)
Freut mich das es bei Dir läuft. Mir waren vorallem die Anzeige der Löschwasserentnahmestellen wichtig.

**Comment by windele** [comment]
Mit der aktuellen Version unserer Software können wir für die Feuerwehren in Bayern den BayernAtlas verwenden - hierzu werden die Koordinaten von der Leitstelle verwendet. Dies war für uns die beste Lösung, da so auch Koordinaten aus Handyortungen oder Einsätze auf Bundesstraßen/Autobahnen abbildbar sind.
