### ISSUE TITLE
Tippfehler Installationsanleitung Raspi

### ISSUE THREAD

**Issue by zaertl** [windele/alarmdisplay-ffw#27]
In der Anleitung, wie man die Software auf einen Raspberry Pi installiert, enthält die Zeile 

sudo apt-get install php-common php-cgi php php-curl mysql-server mysql-client php-mysql wkthmltopdf

einen Tippfehler. Muss wkhtmltopdf heißen.

**Comment by windele** [comment]
wurde soeben korrigiert -- **Danke** für das Feedback!
