### ISSUE TITLE
Vorschlag Beispielfax

### ISSUE THREAD

**Issue by zaertl** [windele/alarmdisplay-ffw#28]
Wird sich aus (div. Gründen) vmtl. schwierig gestalten, aber könnte man der Software ein Beispielfax beilegen?

Hintergrund:
Man könnte so nach der Installation erst mal überprüfen, ob die Pfade zur Fritzbox ect. alle richtig sind, bevor man die Werte an das eigene Fax anpasst. Wir wissen glaube ich alle, je mehr man ändert, desto größer die Gefahr einen Tippfehler zu begehen. Und dann wird es oft schwierig rauszufinden, worans liegt.
Zusätzlich wär es für den einen oder anderen vlt. anhand eines Beispiels auch einfacher die Software an das eigene Faxlayout anzupassen. Scheinbar kocht da jede ILS ihr eigenes Süppchen (zumindest bei meiner Heimat-ILS Amberg).

Wenn gewünscht könnte ich rund 38 tif/box Kombinationen anbieten (von oben genannter ILS), trainiert mit der Sprache ILS und tesseract 3.0.4.

**Comment by windele** [comment]
Hallo,

meine Beispielfaxe habe ich aus Datenschutzgründen nicht veröffentlicht - ich denke, da wird unsere ILS nicht so begeistert sein. 
Aber es stimmt was Du sagst - je mehr man ändert, desto mehr geht schief im Eifer des Gefechts :-)

Man könnte ja ein universelles Fax als PDF machen, das man als Beispiel beiliegt und einfach zum Testen in das FritzBox(faxbox)-Verzeichnis kopiert werden kann.

Ich habs aufgeschrieben und wenn ich wieder Zeit habe, mache ich mich mal daran. Danke für den Vorschlag!

**Comment by windele** [comment]
Hallo,

im Verzeichnis  `configuration` ist jetzt ein PDF, das von der Struktur wie unsere Einsatzfaxe aussieht.

Viel Spaß beim Probieren!
