### ISSUE TITLE
ImageMagick-7 problem

### ISSUE THREAD

**Issue by IBES1410** [windele/alarmdisplay-ffw#30]
Hi zusammen, 
Ich versuche gerade das ganze auf einem pi4 zum laufen zu bringen.
Leider wird hier nicht Imagemagick-7 installiert sonder Imagemagick-6. 

Kann mir hier jemand weiterhelfen was falsch laufen könnte?

Sobald es auf dem PI4 läuft, kann ich gerne das Iso hier mit zur Verfügung stellen. Wenn das ok ist für Stefan!

VG
Sebastian

**Comment by zaertl** [comment]
Wenn du es regulär über die Paketverwaltung installieren willst, wird dir immer für dein System das höchst mögliche installiert. Wenn du nicht weißt, wie man so was händisch installiert, lass es lieber. Du tust dir keinen Gefallen und machst vmtl mehr kaputt und hast einen höheren Arbeitsaufwand, wie es im Verhältnis zum Ergebnis steht. Meine Erfahrung.

**Comment by windele** [comment]
Hallo,

nun kann ich mich auch mal wieder zu Wort melden - leider komme ich aktuell wegen Nachwuchs kaum dazu, was für die Software zu tun oder Verbesserungen zu begleiten.

Es freut mich, dass so viele mit dazu beitragen wollen, das Programm weiterzuentwickeln. Jede Hilfe ist gern gesehen und bringt uns alle weiter.
Ich habe kein Problem damit, wenn jemand fertige Images produzieren möchte - aber wie @zaertl schon in einem anderen Thread geschrieben hat - die alten Raspberrys laufen einwandfrei.

Ich wünsche Euch allen schöne Weihnachten, viel Gesundheit im neuen Jahr und für Eure Feuerwehren wenige und vor allem unfallfreie Einsätze!

Stefan

**Comment by IBES1410** [comment]
Ok, das mit dem PI4 leg ich mal zurück.

@windele ich habe jetzt auf einen 3b+ dein Image laufen. 
Ich hänge wieder an ImageMagick. Laut deiner Anleitung sollte ja ImageMagick-7 laufen. In dem Image ist aber ImageMagick-6 vorhanden. Und der policity.xml von dem 6er kann ich die Zeile nicht finden die man ja ändern soll. 
Ich erhalte immer die Fehlermeldung "tesseract error in pixreadmem size <12"
Kann mir hier jemand weiterhelfen?

**Comment by androbey** [comment]
@IBES1410 
Ich würde an deiner Stelle mal folgende Alternative ausprobieren. 

Ich setze statt ImageMagick Ghostscript ein. Das funktioniert problemlos und ist bei mir sogar (auf einem 3b+) um ein Vielfaches schneller! 

Dazu einfach mit `sudo apt-get install ghostscript` das Paket installieren. Vorher am besten den Pi updaten (`sudo apt-get update` und `sudo apt-get dist-upgrade`). 

Anschließend musst du die [Zeile 32 im Fritzbox Fax überwachen Skript ](https://github.com/windele/alarmdisplay-ffw/blob/master/fritzbox/fritzbox_fax_ueberwachen.sh#L32) mit folgendem Inhalt ersetzen:

`gs -o $FAXTIFF -sDEVICE=tiffg4 $FILE`

Damit sollte hoffentlich auch dein Tesseract Fehler weggehen. Ich empfehle vor dem Ausprobieren einen kompletten System-Neustart.

**Comment by windele** [comment]
Danke für den Beitrag mit GhostScript. Das funktioniert bei meinen Tests wirklich schneller! 
Man lernt nie aus, ich hab den Tipp gleich in den Code übernommen.

**Comment by IBES1410** [comment]
Hallo zusammen, 
ich habe das ganze jetzt doch auf dem Raspi4 zu laufen gebracht. Läuft fast schon perfekt... -Fast. 
Ich hänge mal wieder an der Texterkennung. Und zwar schaffe ich es nicht das Straße und Hausnummer sowie das Stichwort "B4" erkannt wird... 
Ich kapier nicht was ich noch ändern muss. Denke aber ich bin im readfile.php schon richtig...
Ich wäre echt dankbar um Hilfe damit ich das mal im Live Betrieb testen kann. 
Gerne kann ich auch das Fax per PN mal verschicken. 
@windele kann man mit dir per Mail in Kontakt treten? Wenn ja, wo finde ich diese?

Hier mal ein Ausschnitt unseres Faxes der ILS Amberg. Natürlich alles relevante ausgeschnitten...

![Alarmfax geschwärzt](https://user-images.githubusercontent.com/59007418/76337761-1d3a6880-62f8-11ea-818e-ace6610f894e.png)
